### ISSUE TITLE
Provide option to not follow 302 redirects

### ISSUE THREAD

**Issue by aaronpk** [quark-zju/unshorten#7]
When un-shortening a URL like http://t.co/uQVbsZ4aL1, I actually want the end result to be the URL before the 302 is returned. 302 is a temporary redirect, so when un-shortening URLs to include the "final" URL in logs, the final archived URL should not be the result of the temporary redirect. I would be fine with this as an option rather than as the default behavior.

**Comment by quark-zju** [comment]
Hi, I added `follow_codes` option. You can set it by

```ruby
Unshorten::DEFAULT_OPTIONS[:follow_codes] = [301]
```

Or per request:

```ruby
Unshorten['http://t.co/uQVbsZ4aL1', :follow_codes => [301]]
```

Hope that helps :)

**Comment by aaronpk** [comment]
That's great, thanks!! What's the best way to use this before it's published on rubygems?

**Comment by aaronpk** [comment]
oh nevermind, it looks like you just published it. Thanks again!
